[tool.poetry]
name = "aoc2022"
version = "0.1.0"
description = ""
authors = ["Jason Simeone <jay@classless.net>"]

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
